### ISSUE TITLE
docker版，tar命令无 --preserve-permissions参数

### ISSUE THREAD

**Issue by tanzhixu** [linclin/gopub#1]
cd /tmp/simu/go-test-20180410-101436 && tar  --preserve-permissions -czf /tmp/simu/go-test-20180410-101436.tar.gz .

执行结果:
tar: unrecognized option: preserve-permissions
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

Usage: tar -[cxtZzJjahmvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
	c	Create
	x	Extract
	t	List
	f	Name of TARFILE ('-' for stdin/out)
	C	Change to DIR before operation
	v	Verbose
	Z	(De)compress using compress
	z	(De)compress using gzip
	J	(De)compress using xz
	j	(De)compress using bzip2
	a	(De)compress using lzma
	O	Extract to stdout
	h	Follow symlinks
	m	Don't restore mtime
	exclude	File to exclude
	X	File with names to exclude
	T	File with names to include

错误:exit status 1

=============

**Comment by gaoyue1989** [comment]
使用的镜像不支持此命令,现在docker版已经去掉,可以重新拉去最新镜像

**Comment by linclin** [comment]
以前是用centos做基础镜像,由于镜像超过1.4G,替换了alpine基础镜像,alpine镜像不支持此命令.已去掉此参数

**Comment by tanzhixu** [comment]
用的就是最新版，k8s yaml里写的：lc13579443/gopub:latest

**Comment by linclin** [comment]
重新拉取一下,新打包的镜像
