### ISSUE TITLE
docker启动数据库是空的 lc13579443/gopub:latest版本

### ISSUE THREAD

**Issue by jnuc093** [linclin/gopub#13]
1、拉取了版本:
lc13579443/gopub:latest	

`sudo docker run --name gopub -e MYSQL_HOST=127.0.0.1 -e MYSQL_PORT=3306  -e MYSQL_USER=root -e MYSQL_PASS=root -e MYSQL_DB=walle -p 8192:8192  --restart always  -d   lc13579443/gopub:latest `

数据库数据没有初始放进去。

2、数据库中表不存在或者用户不存在的时候
点击登录按钮一直显示"正在登录中"

**Comment by gaoyue1989** [comment]
docker log gopub 看下日志
MYSQL_HOST=127.0.0.1 mysql在docker里面应该不是127.0.0.1
