### ISSUE TITLE
多个项目同时发布的时候，有几率出现其中一个上线单读到别的项目配置的情况

### ISSUE THREAD

**Issue by jmjoy** [linclin/gopub#40]
多个项目同时发布的时候，有几率出现其中一个上线单读到别的项目配置的情况

**Comment by linclin** [comment]
请提供项目配置截图和执行日志，以及如何判断读到其他项目配置的依据

**Comment by jmjoy** [comment]
跑的是world项目，可报错读的是library项目的目录，从两个项目的时间戳可以看出两个上线单是同时进行的
![gopub问题](https://user-images.githubusercontent.com/8677974/58773338-3ab30700-85ef-11e9-81ee-d34bebd58644.png)

**Comment by linclin** [comment]
请提供项目配置截图

**Comment by linclin** [comment]
第一行命令已经很清楚了，你代码目录配置错了

**Comment by jerry0huang** [comment]
library项目配置
![image](https://user-images.githubusercontent.com/31594415/58860680-3ebe5200-86df-11e9-8642-e91e7dc29760.png)
![image](https://user-images.githubusercontent.com/31594415/58860692-47af2380-86df-11e9-9aa7-f4eb0c0df391.png)

**Comment by jerry0huang** [comment]
world项目配置
![image](https://user-images.githubusercontent.com/31594415/58860759-66151f00-86df-11e9-8bdd-a9f05e316294.png)
![image](https://user-images.githubusercontent.com/31594415/58860767-6c0b0000-86df-11e9-840e-49a05569e38f.png)

**Comment by jerry0huang** [comment]
world项目配置
![image](https://user-images.githubusercontent.com/31594415/58860987-f5bacd80-86df-11e9-8eca-8a54e47878c6.png)
![image](https://user-images.githubusercontent.com/31594415/58861005-00756280-86e0-11e9-9b05-a6d530c2e9c6.png)

**Comment by linclin** [comment]
这不是原版gopub,请下载release中的二进制运行
